# Generated by Django 4.1.1 on 2023-09-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManagementSystemAPIs', '0002_alter_registeruser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Summary',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Body',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
