# Generated by Django 4.1.1 on 2023-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManagementSystemAPIs', '0003_task_summary_alter_task_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Document',
            field=models.FileField(null=True, upload_to='pdf_files/'),
        ),
    ]
